version: 2
updates:
  # Enable Dependabot for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "nexus-team"
    assignees:
      - "nexus-team"
    commit-message:
      prefix: "security"
      include: "scope"
    # Only create PRs for security updates and major version updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
    # Group related updates
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
      major-updates:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-major"

  # Enable Dependabot for Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "nexus-team"
    assignees:
      - "nexus-team"
    commit-message:
      prefix: "security"
      include: "scope"

  # Enable Dependabot for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "nexus-team"
    assignees:
      - "nexus-team"
    commit-message:
      prefix: "security"
      include: "scope"

  # Enable Dependabot for Terraform
  - package-ecosystem: "terraform"
    directory: "/infrastructure/terraform"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "nexus-team"
    assignees:
      - "nexus-team"
    commit-message:
      prefix: "security"
      include: "scope"
