apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nexus-backend.fullname" . }}-config
  labels:
    {{- include "nexus-backend.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  PORT: {{ .Values.env.PORT | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  # Add other non-sensitive configuration here
