packages:
  - 'apps/*'
  - 'packages/*'
  - 'libs/*'
  - 'configs/*'
  - 'docs'
  - 'templates/*'
  - 'examples/*'
  - 'services/*'
  - 'components/*'
  - 'utils/*'
  - 'types/*'
  - 'schemas/*'
  - 'tests/*'
  - 'scripts/*'
  - 'plugins/*'
  - 'themes/*'
