# Staging Environment Outputs
# These outputs provide access to staging infrastructure resources

# VPC Outputs
output "vpc_id" {
  description = "ID of the VPC"
  value       = module.vpc.vpc_id
}

output "vpc_cidr_block" {
  description = "CIDR block of the VPC"
  value       = module.vpc.vpc_cidr_block
}

output "private_subnet_ids" {
  description = "IDs of the private subnets"
  value       = module.vpc.private_subnet_ids
}

output "public_subnet_ids" {
  description = "IDs of the public subnets"
  value       = module.vpc.public_subnet_ids
}

# EKS Outputs
output "cluster_id" {
  description = "EKS cluster ID"
  value       = module.vpc.cluster_id
}

output "cluster_arn" {
  description = "EKS cluster ARN"
  value       = module.vpc.cluster_arn
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.vpc.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = module.vpc.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module"
  value       = module.vpc.kubectl_config
  sensitive   = true
}

output "cluster_oidc_issuer_url" {
  description = "The URL on the EKS cluster OIDC Issuer"
  value       = module.vpc.cluster_oidc_issuer_url
}

# Database Outputs
output "db_instance_endpoint" {
  description = "RDS instance endpoint"
  value       = module.vpc.db_instance_endpoint
  sensitive   = true
}

output "db_instance_id" {
  description = "RDS instance ID"
  value       = module.vpc.db_instance_id
}

output "db_instance_port" {
  description = "RDS instance port"
  value       = module.vpc.db_instance_port
}

output "db_subnet_group_id" {
  description = "RDS subnet group ID"
  value       = module.vpc.db_subnet_group_id
}

# Redis Outputs
output "redis_cluster_id" {
  description = "ElastiCache Redis cluster ID"
  value       = module.vpc.redis_cluster_id
}

output "redis_primary_endpoint" {
  description = "ElastiCache Redis primary endpoint"
  value       = module.vpc.redis_primary_endpoint
  sensitive   = true
}

output "redis_port" {
  description = "ElastiCache Redis port"
  value       = module.vpc.redis_port
}

# S3 Outputs
output "s3_bucket_app_assets" {
  description = "S3 bucket for application assets"
  value       = module.vpc.s3_bucket_app_assets
}

output "s3_bucket_backups" {
  description = "S3 bucket for backups"
  value       = module.vpc.s3_bucket_backups
}

output "s3_bucket_logs" {
  description = "S3 bucket for logs"
  value       = module.vpc.s3_bucket_logs
}

# Monitoring Outputs
output "cloudwatch_dashboard_url" {
  description = "CloudWatch dashboard URL"
  value       = module.vpc.cloudwatch_dashboard_url
}

output "cloudwatch_log_group_name" {
  description = "CloudWatch log group name"
  value       = module.vpc.cloudwatch_log_group_name
}

# Load Balancer Outputs
output "alb_dns_name" {
  description = "DNS name of the load balancer"
  value       = module.vpc.alb_dns_name
}

output "alb_zone_id" {
  description = "Zone ID of the load balancer"
  value       = module.vpc.alb_zone_id
}

# Environment Information
output "environment" {
  description = "Environment name"
  value       = var.environment
}

output "region" {
  description = "AWS region"
  value       = var.aws_region
}

output "project_name" {
  description = "Project name"
  value       = var.project_name
}
