name: Environment Validation

on:
  push:
    branches: [main, develop, staging]
    paths:
      - '.env.*'
      - 'scripts/validate-env.js'
      - '.github/workflows/environment-validation.yml'
  pull_request:
    branches: [main, develop, staging]
    paths:
      - '.env.*'
      - 'scripts/validate-env.js'

jobs:
  validate-environments:
    name: Validate Environment Configurations
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Validate Development Environment
        run: node scripts/validate-env.js development
        
      - name: Validate Staging Environment
        run: node scripts/validate-env.js staging
        
      - name: Validate Production Environment
        run: node scripts/validate-env.js production
        
      - name: Validate Test Environment
        run: node scripts/validate-env.js test
        
      - name: Check for sensitive data exposure
        run: |
          echo "Checking for exposed secrets in environment files..."
          if grep -r "sk_live\|pk_live\|rk_live" .env.* 2>/dev/null; then
            echo "❌ Live API keys detected in environment files!"
            exit 1
          fi
          
          if grep -r "password.*=.*admin\|secret.*=.*secret" .env.* 2>/dev/null; then
            echo "⚠️ Weak passwords detected in environment files"
          fi
          
          echo "✅ No obvious secret exposure detected"
          
      - name: Generate Environment Documentation
        run: |
          echo "# Environment Configuration Documentation" > env-docs.md
          echo "" >> env-docs.md
          echo "## Available Environments" >> env-docs.md
          echo "" >> env-docs.md
          for env in development staging production test; do
            echo "### $env" >> env-docs.md
            echo "" >> env-docs.md
            echo "Configuration file: \`.env.$env\`" >> env-docs.md
            echo "" >> env-docs.md
            if [ -f ".env.$env" ]; then
              echo "Variables defined: $(grep -c "^[A-Z]" .env.$env || echo 0)" >> env-docs.md
            else
              echo "❌ Configuration file missing" >> env-docs.md
            fi
            echo "" >> env-docs.md
          done
          
      - name: Upload Environment Documentation
        uses: actions/upload-artifact@v4
        with:
          name: environment-documentation
          path: env-docs.md
          retention-days: 30
